name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: deploy
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_API_KEY }}@pub.current.posit.team
          namespace: superzip
          dir: |
            ./r/
            ./python/
          require-vanity-path: true
          access-type: all